### ISSUE TITLE
Biota not run, ASM transformer crash

### ISSUE THREAD

**Issue by Bogdan-G** [Dynious/Biota#1]
Biota 0.0.1. Mod not compatible forge 1240,1263,1284,1291,1300,1307,1343,1395,1399,1400. Test with AppleCore(v1.0.0 - v1.1.0) has install and uninstall. Java test version 7 and 8. Win7x64.

[20:52:23] [main/DEBUG] [FML/]: Injecting coremod LoadingPlugin {com.dynious.biota.asm.LoadingPlugin} class transformers
[20:52:23] [main/TRACE] [FML/]: Registering transformer com.dynious.biota.asm.CoreTransformer
[20:52:23] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NoClassDefFoundError: squeek/asmhelper/applecore/ObfRemappingClassWriter
[20:52:23] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at com.dynious.biota.asm.CoreTransformer.<clinit>(CoreTransformer.java:15)
[20:52:23] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[20:52:23] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[20:52:23] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[20:52:23] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at java.lang.reflect.Constructor.newInstance(Unknown Source)
[20:52:23] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at java.lang.Class.newInstance(Unknown Source)
[20:52:23] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88)
[20:52:23] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:101)
[20:52:23] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[20:52:23] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[20:52:23] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.ClassNotFoundException: squeek.asmhelper.applecore.ObfRemappingClassWriter
[20:52:23] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[20:52:23] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at java.lang.ClassLoader.loadClass(Unknown Source)
[20:52:23] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at java.lang.ClassLoader.loadClass(Unknown Source)
[20:52:23] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: ... 10 more
[20:52:23] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.NullPointerException
[20:52:23] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[20:52:23] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: ... 12 more
full fml 1240 log - http://pastebin.com/Zvh00HqX
full fml 1400 log - http://pastebin.com/GnmcMQMZ

What you need to work with mod?

**Comment by Dynious** [comment]
Biota needs a version of AppleCore that has not been officially released yet. You can build the version from their GitHub: https://github.com/squeek502/AppleCore

Keep in mind, everything is WIP.
